version: '3.8'

networks:
  zabbix-monitoring:
    driver: bridge

volumes:
  mariadb_data:
  grafana:

services:
  mariadb-server:
    image: mariadb:10.6.12
    container_name: mariadb-server
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - zabbix-monitoring

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    networks:
      - zabbix-monitoring
    links:
      - mariadb-server
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mariadb-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - mariadb-server

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest
    networks:
      - zabbix-monitoring
    links:
      - mariadb-server
    restart: always
    ports:
      - '80:8080'
    environment:
      - DB_SERVER_HOST=mariadb-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Berlin
      - ZBX_SERVER_NAME=uLinky Corporation
    depends_on:
      - mariadb-server

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.2-ubuntu
    networks:
      - zabbix-monitoring
    links:
      - mariadb-server
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mariadb-server
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    user: root
    networks:
      - zabbix-monitoring
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - /etc:/host/etc:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
