apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://127.0.0.1/api_jsonrpc.php
    isDefault: true
    version: 1
    editable: true
